### ISSUE TITLE
Issue with connection in Chrome

### ISSUE THREAD

**Issue by Shashwat986** [Zarel/Pokemon-Showdown-Client#1013]
I'm not sure if this is the right place to report this issue or not, but here goes:

On Google Chrome v61.0.3163.100, I keep seeing the "You have been disconnected – possibly because the server was restarted." error on loop. When I open the console, I see that this request is throwing a 404.

<img width="818" alt="screen shot 2017-09-29 at 2 03 31 pm" src="https://user-images.githubusercontent.com/5304561/31007931-d7a08680-a51f-11e7-8534-a21f8caf09cd.png">

Any idea what the issue might be?

**Comment by Shashwat986** [comment]
Not reproducible on Safari

**Comment by xfix** [comment]
xhr_send being used is very interesting, seems like the issue may be caused by a proxy not supporting WebSockets (or perhaps a failure to connect to WebSocket before). I cannot reproduce this with `wss://` filter in uBlock (disabling WebSockets forcing XHR to be used).

**Comment by Zarel** [comment]
This is very obviously a proxy. There's nothing we can do if someone else is interfering with your internet connection. However, you may be able to get a clearer error message from whoever is interfering with your internet connection if you go directly to http://sim2.psim.us/

**Comment by xfix** [comment]
I find it interesting that HTTPS is used however. Do you by any chance have an antivirus with SSL filtering option? If so, disable it, it reduces your security by disabling important HTTPS security features as it's likely less secure implementation than an implementation in web browser (for instance, it likely doesn't support HPKP to begin with).
