### ISSUE TITLE
Sound Ocasionally Distorted in Firefox Quantum (57) on Mac OSX 10.12.6

### ISSUE THREAD

**Issue by PmmaGit** [Zarel/Pokemon-Showdown-Client#1046]
Not completely sure why, and i have only noticed it on Showdown so far so it makes me think it might be a combination of how Showdown plays sound + the new Firefox update. 
 
What happens is that, ocasionally when you launch a battle, the sound plays distorted, with noticeable noise and lag, this affects Pokémon cries and the BGM. 

I tried playing a youtube video at the same time and the playback from that one seemed fine.

I'll update this if it happens somewhere else, or if i notice anything new.

EDIT: It seems like its prone to happen on the first battle after you load the page, subsequent seem fine.

**Comment by Zarel** [comment]
I'm not sure this is anything I personally have control over? Maybe try reporting to soundManager or Firefox?

http://www.schillmania.com/projects/soundmanager2/ is the library we use for playing sound.

**Comment by Meeplee** [comment]
I'll look into it, i'm almost sure it isn't an issue on your end by now.
