### ISSUE TITLE
Teambuilder: Add Ability to filter moves by their flags

### ISSUE THREAD

**Issue by FelixRilling** [Zarel/Pokemon-Showdown-Client#1052]
As all moves already have given flags like `contact`, `bite` or `punch` defined in their data, what about the ability to filter for these flags, similar to how you can filter for special/physical/status moves? This would make it much easier to create movesets for pokemon with an ability like Though Claws or Iron Fists.

**Comment by Zarel** [comment]
Why was this closed? Did someone end up doing it?
