### ISSUE TITLE
Zoroark/HealBell

### ISSUE THREAD

**Issue by yuzeh** [Zarel/Pokemon-Showdown-Client#1062]
My understanding of heal bell: the server sends a -curestatus message to the client for each pokemon the client knows about. Zoroark, as always, throws a wrench into things -- the server thinks the client has seen a Zoroark, whereas the client has either

1) not seen a zoroark or
2) seen an illusion.

I haven't read the server code, but given that this doesn't crash all the time with healbell, I can only imagine 2) is the reason.

I've attached a replay log that should fail: [zoroark-heal-bell.txt](https://github.com/Zarel/Pokemon-Showdown-Client/files/1541822/zoroark-heal-bell.txt)

I'm not sure if the fix here should be client or server-side because I'm not familiar with how this is handled in the cartridge games.

**Comment by Zarel** [comment]
I believe it does say "Zoroark was cured" in the cart, but punting to @Marty-D for confirmation.

**Comment by Zarel** [comment]
Also, here's the replay in replay-file mode.

[zoroark-heal-bell.html.zip](https://github.com/Zarel/Pokemon-Showdown-Client/files/1543387/zoroark-heal-bell.html.zip)

**Comment by Marty-D** [comment]
If Zoroark is active and the Illusion is active, it uses the disguise's name, otherwise Zoroark's.

**Comment by Zarel** [comment]
Okay, so then the server's correct; we just need to fix client.

**Comment by yuzeh** [comment]
I'll take a stab at it this weekend if I have some free time.

**Comment by Zarel** [comment]
This would mainly involve revising the `-curestatus` minor message handler, to better handle inactive pokemon?

**Comment by Zarel** [comment]
I think you can pass a "can be inactive" flag to `getPokemon`, which is probably what you want to do.

**Comment by yuzeh** [comment]
So I lied about being able to get to this last week, but I've thought about this a bit more.

> I think you can pass a "can be inactive" flag to `getPokemon`, which is probably what you want to do.

There is a flag to only match inactives, which is implied by passing in `p{1|2}: Name` as the second parameter. However, I don't think that's what we want to do here.

Looks like what we'd want to do in this case is create the Zoroark if it's not already being tracked in the team, no?

**Comment by Zarel** [comment]
There's not enough data to create the Zoroark if it's not already being tracked. I think the actual solution is to fallback to extracting the name from the pokemon identifier, and printing it.

**Comment by yuzeh** [comment]
Great, that seems fairly easy to do!
