### ISSUE TITLE
battle.js: separating state tracking from graphics and sound

### ISSUE THREAD

**Issue by yuzeh** [Zarel/Pokemon-Showdown-Client#1079]
I know this would be a huge project but is there any interest in having this done?

**Comment by Zarel** [comment]
I've thought about doing this in the past, but the general problem is... how?

In general, I don't really have a particularly good way to reconcile good state tracking with animation.

**Comment by yuzeh** [comment]
Wow! It looks like some progress has been made on this since I checked in.

My main interest is creating a headless client, and it looks like I can basically do that making shims to all the UI-related code referenced from `src/battle-*`.

Closing this bug.

**Comment by Zarel** [comment]
Oh yeah, I ended up doing exactly that by separating `battle.ts` from `battle-scene.ts`.

I think if you set `battle-scene.ts` to `animating = false`, you basically don't need to do anything else to make it headless?

**Comment by Zarel** [comment]
Oh wait, there are some other things you need to do. Shimming is probably not a bad approach at the moment, but there are still plenty of improvements left to be made.
