### ISSUE TITLE
Shiny Tapu-Koko is seen as illegal, despite being released in an event

### ISSUE THREAD

**Issue by DeckOfNoobs** [Zarel/Pokemon-Showdown-Client#1122]
Title. Although Shiny Tapu-Koko was released in an [event](http://tapukoko.pokemontcg.com/en-us/) a year ago, it will not be accepted on a team.

I don't know if it's just me being retarded, but I'm pretty sure it's supposed to be accepted as legal?

**Comment by Zarel** [comment]
@Marty-D?

**Comment by Zarel** [comment]
@DeckOfNoobs Shiny Tapu Koko is accepted on teams in PS.

If it doesn't work for you, it's most likely because there is some other aspect of the set that's incompatible with the event.

Can you show me the set, and the error message you get?

**Comment by Zarel** [comment]
(I'm closing because this isn't a bug, but I'll respond to you if you provide the additional information I asked for.)

**Comment by DeckOfNoobs** [comment]
![image](https://user-images.githubusercontent.com/20460754/40580398-552b8562-610b-11e8-890b-40f99be1dcbf.png)
when trying to add shiny tapu koko in OU
happens regardless of what it's holding/moves/etc

**Comment by Zarel** [comment]
Can you show me the set? The error message is most because you are using event moves from event #1, which is not a shiny event.

**Comment by DeckOfNoobs** [comment]
![image](https://user-images.githubusercontent.com/20460754/40580472-cc739e74-610c-11e8-8382-2aca51aea5f9.png)

**Comment by Zarel** [comment]
Aha, I looked more closely.

The error message is because your Tapu Koko is not Timid. The shiny event only distributed Timid Tapu Koko.

**Comment by DeckOfNoobs** [comment]
Huh, that's interesting
Would be helpful if the error message displayed that it needed to be Timid but idk how hard that would be to implement

**Comment by Zarel** [comment]
Yeah, that's really hard to do. The main problem is that it doesn't know how to prioritize the suggestion. If you have a Modest shiny Tapu Koko, should it suggest that you make it Timid, or should it suggest that it make it non-shiny?

Right now the default is to just suggest its first event. I could maybe hardcode a search for shiny events.
