### ISSUE TITLE
Suppressed -ate abilities still change types in move menu

### ISSUE THREAD

**Issue by Storm-Eagle20** [Zarel/Pokemon-Showdown-Client#1132]
When a Pokemon with an -ate ability has their ability disabled by Core Enforcer, Normal-type moves still appear as their respective types when selecting a move.

The color and type shown on the buttons don't match the Normal type after an Aerilate Pokemon has their ability disabled. This is likely true for the other abilities like Pixilate too. Normalize works as all moves except for moves like Revelation Dance act like Normal type moves.

**Comment by Zarel** [comment]
Okay, I also did something about the unwieldingly long title.

**Comment by Zarel** [comment]
@Marty-D Does Core Enforcer have a message when it suppresses an ability? I'm pretty sure Gastro Acid does, and Core Enforcer seems to be pretty similar.

**Comment by Storm-Eagle20** [comment]
To answer your question Core Enforcer does have a message notifying that the enemy's ability was disabled.

**Comment by Marty-D** [comment]
@Zarel It literally starts Gastro Acid's effect, which sends `|-endability|`, which has the start message. I'm talking about checking the volatile in the tooltip code somewhere.

**Comment by Zarel** [comment]
Oh, huh, you're right. I couldn't find the `|-endability|` the last time I looked at a replay, for some reason.
