### ISSUE TITLE
Suppressed No Guard ability still lists moves as '---' accuracy.

### ISSUE THREAD

**Issue by Storm-Eagle20** [Zarel/Pokemon-Showdown-Client#1135]
Same issue as before with -Ates. Core Enforcer disabling No Guard still lists the moves as '---' accuracy even though they are not '---' accuracy.

**Comment by Zarel** [comment]
My fix should have fixed both... let me see what's wrong.

**Comment by Storm-Eagle20** [comment]
https://i.imgur.com/31hezuY.png

Isn't fixed yet. Are you sure this fix applies to No Guard?

**Comment by Zarel** [comment]
Yes, it's intended to apply to the browser version. Good to know, I'll need to investigate this closer.

**Comment by Storm-Eagle20** [comment]
Do you want me to retry it now? Or does the patch not apply until a server restarts? I'm assuming patches do not apply retroactively.

**Comment by Zarel** [comment]
Client patches apply upon refresh. You can retry if you want, but I actually did test my fix this time.

**Comment by Storm-Eagle20** [comment]
I tried it and it works. Thanks.
