### ISSUE TITLE
Support headless client

### ISSUE THREAD

**Issue by yuzeh** [Zarel/Pokemon-Showdown-Client#1148]
Picking up where we left off on #1137: I'm interested in implementing a headless client in the PSC repo.

This will let other projects use the battle state inference code that's already been implemented in this repo in a modular fashion. More importantly, it allows for *unit testing* of the battle state inference code (there doesn't seem to be any such testing currently).

My vision of how this will work:

* Per https://github.com/Zarel/Pokemon-Showdown-Client/pull/1137#issuecomment-410474024, `new Battle(null, null)` (or `new Battle()`) creates a headless Battle object.
* On constructor call, a stub `BattleScene` object is created that basically no-ops all of its methods. This can be done in at least two ways:
    * Common interface between a handwritten `StubBattleScene` class (along with a handwritten `StubPokemonSprite`) and the existing `BattleScene` class, or
    * ES6 `Proxy`.
* Unit tests are written to demonstrate how this should be used. I'm not quite sure myself how this is supposed to be done, but I've had luck doing the following:
```js
battle.activityQueue.push(message);
battle.play();
battle.fastForwardTo(-1);
```

If this sounds good, I can start working on a PR.

**Comment by Zarel** [comment]
Yeah, sounds good to me!

**Comment by yuzeh** [comment]
@Zarel what do you think about using a common interface vs a proxy object for the stub?

**Comment by Zarel** [comment]
I'd prefer to retain IE7 support.
