### ISSUE TITLE
testclient.html does not work

### ISSUE THREAD

**Issue by killemall420** [Zarel/Pokemon-Showdown-Client#1150]
So I've been fooling around with the client, making some custom changes and all that. However, yesterday it just stopped working, and I can't get it to work. Using node.js version 9.11.1 and npm version 5.6.0 for clarification. Here's the problem that comes up:
![capture](https://user-images.githubusercontent.com/19376407/46232166-4c475f00-c33c-11e8-9685-db702479c765.PNG)
Here's the cmd window to build the client:
![capture 2](https://user-images.githubusercontent.com/19376407/46232198-62edb600-c33c-11e8-9a7a-24ef4f679532.PNG)
And here's the errors on the window:
![capture 3](https://user-images.githubusercontent.com/19376407/46232213-6d0fb480-c33c-11e8-8bf1-b8b9b59cd94e.PNG)
(images censored for privacy)
this should be fixed if anyone is going to help work on the client

**Comment by Zarel** [comment]
Hm, it still works on my computer.

I see a `^C`? I guess the errors happened because you interrupted the build before it finished? Rebuild it and don't do that, I guess...

**Comment by killemall420** [comment]
Okay, I think I found the problem: the client takes way too long to build the graphics.js file, which must prevent the paste this screen from appearing. So I think a fix for this would be to try to make the node build build the graphics.js faster? I don't know how possible that would be tho...

**Comment by Zarel** [comment]
Oh, yeah, Babel has a lot of trouble with `graphics.js`.

**Comment by Zarel** [comment]
Specifically, `battle-animations-moves.ts`. I was thinking about making the API more terse, but we should probably figure something out with splitting it up either way.

**Comment by Zarel** [comment]
I forced on Babel Compact mode. Can you compile now?
