### ISSUE TITLE
"Download Replay" on Unregistered Server gives bad redirect

### ISSUE THREAD

**Issue by sandyllama** [Zarel/Pokemon-Showdown-Client#1171]
Noticed this started happening yesterday on an unregistered server that I host. I had users trying to download replays of games that they had played for a league, but whenever they hit the "Download Replay" button that appears after a match, the page would redirect to https://replay.pokemonshowdown.com/.

Before yesterday, this would simply download the .html file of the game.

**Comment by Zarel** [comment]
I admit, I did that mainly just to try out the issue transfer feature. Looks like it works well.

**Comment by Zarel** [comment]
Fixed in https://github.com/Zarel/Pokemon-Showdown-Client/commit/6640c323f00e92d792433d69a7acb5a19e59ba30
