### ISSUE TITLE
pixelation on retina screens

### ISSUE THREAD

**Issue by wlgranados** [Zarel/Pokemon-Showdown-Client#1196]
I think this issue only occurs on when I have a triple monitor setup using my Mac, and the pixelation makes sprites really stretched. When I only use the retina screen the pixelation doesn't seem to be too noticeable.  Not quite sure if this is intentional, judging from 
e45256d98b8d7913614534218cf4945fcdb5bdbe . 

**Screenshots when Retina displayed on other monitors**
![screen shot 2018-12-18 at 5 27 41 am](https://user-images.githubusercontent.com/5634714/50148653-0dfc7480-0287-11e9-8344-5b2434f60410.png)
![screen shot 2018-12-18 at 5 29 26 am](https://user-images.githubusercontent.com/5634714/50148669-18b70980-0287-11e9-8ac1-aed561c0a8b7.png)
**Screenshot when only on Retina screen**
<img width="293" alt="screen shot 2018-12-18 at 5 43 22 am" src="https://user-images.githubusercontent.com/5634714/50148983-f1147100-0287-11e9-85c4-30c853916b69.png">

Using Chrome on MacOS

**Comment by Zarel** [comment]
Yeah, pixelation is kind of awkward on zoom factors between 100% and 200%.

Unfortunately, nearly all Retina screens are 200% and need to be optimized for.

I don't even think browsers have a way to detect zoom level, so we can't even manually turn off pixelation for those zoom levels.

**Comment by xfix** [comment]
@Zarel I think you want `window.devicePixelRatio` here.

**Comment by Zarel** [comment]
Actually, this is doable with media queries.

**Comment by Zarel** [comment]
You seem to not like the zoom factors below 100% either, though. Which I guess is a matter of taste. I think they don't look too bad.
