### ISSUE TITLE
Decimal places of accuracy are not rounded

### ISSUE THREAD

**Issue by FelixRilling** [Zarel/Pokemon-Showdown-Client#1233]
![511d99](https://user-images.githubusercontent.com/3207763/53043591-1771ab00-3489-11e9-9363-5f576be37112.png)
If the accuracy of a move is modified and has decimal places, the full decimal places are shown while they used to be rounded to (I think) 2 decimal places instead.

**Comment by Zarel** [comment]
Fixed in #1232

**Comment by Slayer95** [comment]
I saw this recently with Gravity.
