### ISSUE TITLE
Feature request: Importing sets from Smogon analyses / "bookmarked" sets

### ISSUE THREAD

**Issue by jamesqo** [Zarel/Pokemon-Showdown-Client#1337]
In the teambuilder, I think the spread guesser should be replaced with a dropdown control that lets you select from the sets listed on the Smogon analysis. This would save a lot of time for people who want to quickly throw a team together with standard sets, as it's now 6 button clicks instead of 6 times visiting the analysis webpage, scrolling down to the set you want, clicking Export, copying, going back, clicking Import, and pasting the set.

I also propose adding a "bookmarking" feature so that the user can do this with sets that aren't in the analysis: if the user has a custom EV spread they like for example, they can just make a set with that spread, click a "Bookmark" button and fill out a name for the set. Afterwards when the user clicks the dropdown control, the set will be listed alongside the ones from the Smogon analysis.

**Comment by Zarel** [comment]
Better integration with Smogon sets is a complicated issue. I feel like "copy/paste over Smogon sets" is easy enough. I've had mixed feelings about really tight integration (I want to encourage creativity, to an extent).

I wouldn't say no to well-done integration that isn't too pushy about it, but I don't feel like leaving up feature request issues on the subject of integration.

**Comment by Zarel** [comment]
As for "bookmarking" sets, a Box feature is planned.

**Comment by jamesqo** [comment]
> Better integration with Smogon sets is a complicated issue. I've had mixed feelings about really tight integration (I want to encourage creativity, to an extent).

What downsides do you see with tighter integration?

> I feel like "copy/paste over Smogon sets" is easy enough.

For me personally, I feel like it would save a lot of time, since when building a team I tend to fill out the set details of each member as I go along. Each time I change my mind and swap out one Pokemon for another, I end up deleting everything that I just typed in and have to re-paste/re-type it. For example, sometimes I have a train of thought like "hmm Salamence looks good here *fills in set for Salamence* wait Zygarde is better *fills in set for Zygarde* oh, wait Zygarde can't do X actually *fills back in Salamence*" It's not much time to copy/paste from the analysis for a single Pokemon, but it can add up. Just to build a team full of standard mons, you need to visit 6 different webpages, scroll down to the set you need, and copy/paste which takes 1-2 mins (assuming your wifi isn't slow), when you could just be clicking a dropdown 6 times and be done in 20 secs.

**Comment by Zarel** [comment]
> > Better integration with Smogon sets is a complicated issue. I've had mixed feelings about really tight integration (I want to encourage creativity, to an extent).
> 
> What downsides do you see with tighter integration?

> >  (I want to encourage creativity, to an extent).

**Comment by scheibo** [comment]
Tighter [Smogon + Pokemon Showdown integration](https://pkmn.cc/smogon-ps-integration) is something I've been thinking about as well, but I agree with Zarel that this is a complicated issue for a number of reasons (not all of them being technical). Rest assured, tech staff is aware of this feature and will work towards making the teambuilding process as efficient and optimal as possible. Thanks for your suggestion.
