### ISSUE TITLE
COIL only for specific ladders

### ISSUE THREAD

**Issue by Antar1011** [Zarel/Pokemon-Showdown-Client#157]
COIL should only show up for selected ladders, and each ladder should have unique values for "B." I'm not sure how to do this in php.

What I'm thinking would be optimal is to have ladder.php and client-chat.js consult a separate "COIL" file that's just a lookup table that looks something like:

```
oususpecttest:75
lcsuspecttest:43
```

and, if the formatid isn't present in the list, it doesn't make the column, and if it does, it uses the specified value for "B" for the COIL calculation. That way, instead of editing two files in two different languages any time we want a new coil for a new suspect test, we can just edit that one file.

**Comment by Zarel** [comment]
I believe this is done now?

**Comment by Zarel** [comment]
nvm it still isn't... we should really have gotten on that...

**Comment by Zarel** [comment]
Well, due to COIL being massively misused, PS no longer supports COIL, so I guess we don't have to work on this anymore.
