### ISSUE TITLE
CSS3 rules are deleted

### ISSUE THREAD

**Issue by Kingfisher7** [Zarel/Pokemon-Showdown-Client#248]
Posting in the right repository this time I hope. 
Well, I've never been able to use things like linear-gradient(), but other CSS3 things like border-radius and box-shadow are just removed too.
These are things added through custom.css. I think it would add a good amount of design possibilities if we could use these kinds of things.

**Comment by Dubstepper** [comment]
Any idea when this will be fixed?

**Comment by Zarel** [comment]
Probably never, unless you do it yourself. Feel free to do it yourself, though; PS is open-source.

**Comment by kotarou3** [comment]
Note for people potentially wanting to fix this for us, fixing this will involve two parts:
1. Change the client to pull the CSS directly from `server/custom.css` and sanitise it, before loading it onto the page
2. Updating `Tools.sanitizeHtml()` to not filter out all CSS. Best done by switching out the current sanitiser completely with caja

**Comment by Zarel** [comment]
I thought we _were_ using Caja?

**Comment by kotarou3** [comment]
Definitely not, for `custom.css`.

For `Tools.sanitizeHtml()`, though, it does seem we're using caja, but we're not allowing css through for some reason, so that should be fixed

**Comment by Zarel** [comment]
(I don't think a lack of support for something can be called a bug)

**Comment by Slayer95** [comment]
More like incomplete support, but let's not bikeshed the labeling.

**Comment by Zarel** [comment]
Our support for CSS2 is mostly complete.

**Comment by Zarel** [comment]
Fixed in #919
