### ISSUE TITLE
Modularizing client js files with RequireJS?

### ISSUE THREAD

**Issue by dillonforrest** [Zarel/Pokemon-Showdown-Client#25]
Hey guys!  I'm new here.  Love this battle simulator so much!!  :)

I realized that the javascript files are really massive.  I'm interested in submitting a pull request to implement RequireJS.  I'm wondering, are you guys openminded to that?  Have you guys discussed this before?

**Comment by rainbowshrimp** [comment]
It may be better to use Browserify instead since it follows the node.js style of using require. It is a cleaner way of loading dependencies into the app.

http://browserify.org/

**Comment by Zarel** [comment]
Browserify isn't compatible with the version of NWjs we're using on the desktop client, as I just learned... :/

**Comment by Zarel** [comment]
We can manually fix it, but ick.

**Comment by Zarel** [comment]
This hasn't been done in over a year, so I'm guessing this is dead. Any major client overhaul should probably be done with a TypeScript refactor, anyway.
