### ISSUE TITLE
Implement ability activation popups

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown-Client#315]
Overdue from BW.

**Comment by Zarel** [comment]
Honestly, the "[Pokemon's ability]" text in the battle log is good enough for me.

**Comment by ascriptmaster** [comment]
Either way, the server side should be sending some messages relating ability activation, and then the client can show [POKEMON's ABILITY]. Then later, if we really want ability activation popups, we can add that.

**Comment by Zarel** [comment]
Closing because afaik the "[Pokemon's ability]" text is good enough.
