### ISSUE TITLE
Cancel doesn't work if the only battle request is the own

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown-Client#316]
There are some cases when it's evident that the battle has only a single request pending. Under such circumstances, the battle will proceed as soon as the player makes their choice, and any subsequent <code>/undo</code> messages will be invalid. As the option to cancel doesn't <i>really</i> exist then, it follows that (at least) for those circumstances, the cancel button should either be
- Removed or disabled
- Reworked (maybe implement a safety delay to choices so that the player may cancel their decision until the delay finishes and the decision is sent).

Which one?

**Comment by Zarel** [comment]
Mainly we want to send the "cancelable period is over" message as soon as possible. Immediately sending `|` to both players once both decisions are in, without waiting for sim processes to respond, is probably the best solution.

**Comment by Slayer95** [comment]
That's probably a good approach for the cases when you could cancel if you clicked fast enough.

What this issue is about is for cases when you could never actually cancel, i.e. there was no cancelable period at all. e.g.: if you are prompted to switch on U-Turn usage, or if your Pokémon faints and no other player has to switch another Pokémon in.

**Comment by Zarel** [comment]
Oh, you can fix that, too.

**Comment by ascriptmaster** [comment]
Maybe the request message JSON can have a field that goes `nocancel:true` if you disallow cancelling.

**Comment by Zarel** [comment]
Would be a good way to do it.

**Comment by Slayer95** [comment]
I'm considering a fully client-side solution for this.
Given that https://github.com/Zarel/Pokemon-Showdown/issues/1452 turns out well, the client will always be able to know if the opponent has Pokémon available to replace any fainted slots. If the current request type is <code>switch</code> and the switching out Pokémon are fainted, then we know when not to display the Cancel button.

Modifying the request to prevent cancel has its merits, however, as removing the Cancel feature from any metagame objecting its existence (think of VGC) would be straightforward. However, for such cases I'd support making <code>|rule|</code> operational.

**Comment by Zarel** [comment]
I'd modify the request to prevent cancel; I like having request-relevant data in the request itself.

**Comment by Slayer95** [comment]
Fine. I'll do this as soon as I get my hands on a computer with Node.
