### ISSUE TITLE
Locally keep track of chat and PMs

### ISSUE THREAD

**Issue by KitKasai** [Zarel/Pokemon-Showdown-Client#345]
I was thinking it'd be interesting if the client could log chat from all chatrooms the user is in and all pms the user receives so that the next time the user opens the client there is a longer history of what is said in chat rooms than what is normally received from the server. 

This is probably not as important for chatrooms as there is a lot of lines being said and there would be major gaps in the client's local history, but I think it would be a great thing for PMs. Right now, since PMs aren't logged by the client, they disappear when the client is closed, which can be frustrating if you accidentally navigate to another page or something while having a conversation with someone. It's useful to have a history of PMs with other people (I'm envisioning something like the way skype chat works) so you can refer to comments made in the past and so you don't accidentally lose the chat history like I mentioned above.

**Comment by kotarou3** [comment]
The way Skype works is it saves all chat logs on Skype's servers, and downloads them to your computer if it detects you have an outdated version.
Unfortunately, we don't like invading people's PM privacy, nor do we have servers as big as Skype, so we can't copy what Skype does.

Instead, we could just save the chat logs locally in DOM storage, but it would mean if you switch browsers/computers, it wouldn't come with you

**Comment by KitKasai** [comment]
That's basically what I was envisioning, keeping chat logs stored locally.

**Comment by Zarel** [comment]
This is actually a pretty good idea.

**Comment by Slayer95** [comment]
Note that the PS desktop client already has this feature.

**Comment by panpawn** [comment]
>Unfortunately, we don't like invading people's PM privacy, nor do we have servers as big as Skype, so we can't copy what Skype does.

Times have changed, and we now log PMs on the server.  We shouldn't have to save PMs in both the server and in people's localstorage; we should do it as Skype does.

**Comment by Zarel** [comment]
No, that's not the problem, the problem is that PM logging logs to log files, not a database that's easy to retrieve info from.

Database access is generally the issue here.

**Comment by Zarel** [comment]
This is a good idea, but since no one is going to code it, it probably won't get implemented. My long-term solution is still server-side databases, which are coming sooner or later.
