### ISSUE TITLE
Pokemon Showdown doesn't support ÜÄÖ and probably other special symbols

### ISSUE THREAD

**Issue by Konstamokh** [Zarel/Pokemon-Showdown-Client#349]
Sometimes I want to give my Pokemon German nicknames and sadly those symbols are not working with Pokemon Showdown. Would be great to get support for this for the international audience.

**Comment by Zarel** [comment]
I've been meaning to do this for quite a while, will move it up the to-do list.

**Comment by xur86x** [comment]
Thanks :)

**Comment by Slayer95** [comment]
Done in https://github.com/Zarel/Pokemon-Showdown/commit/de9c3847fd88e14284e53f286dd5cfc796ef6691
