### ISSUE TITLE
BW animations strech

### ISSUE THREAD

**Issue by Layell** [Zarel/Pokemon-Showdown-Client#372]
http://i.imgur.com/MEDXPBD.png

https://github.com/Zarel/Pokemon-Showdown-Client/commit/299777f297254e39399bcd42ab5738e67384c6c6

Try switching to bw animated and go to a battle, still loading xy stuff.

I'm not sure what broke here but I know part of the original addition was that there would be a sprite reload every time we selected bw animations over xy stuff. If it is this commit that broke it can we get it reverted until it is fixed?

**Comment by QuiteQuiet** [comment]
I can't seem replicate this. Everything I try loads the gen 5 sprite sizes as expected selecting bw sprites and going to battle. Are there any more details to this?

http://puu.sh/hFAms

**Comment by Layell** [comment]
Try to have the option for animated bw sprites be your default right when you load PS.
