### ISSUE TITLE
Notification bug on Android devices with Google Chrome

### ISSUE THREAD

**Issue by Freigeist** [Zarel/Pokemon-Showdown-Client#374]
The used Notification feature of Showdown, leads to following error in Google Chrome on Android devices:

`Uncaught TypeError: Failed to construct 'Notification': Illegal constructor. Use ServiceWorkerRegistration.showNotification() instead. (client.js?c0d807c0:1768)`

Using `new Notification()` with Google Chrome on Android devices isn't supported anymore

Relevant chromium issue: https://code.google.com/p/chromium/issues/detail?id=481856

**Comment by Zarel** [comment]
How annoying. :|

**Comment by Zarel** [comment]
iirc this was "fixed" recently, by which I mean the relevant code was wrapped in a `try`-block.

**Comment by Zarel** [comment]
Ah yes in here: 30da43cabfde9e272

**Comment by Zarel** [comment]
The real fix is to support Web Workers and properly implement Android support, but that's way back-burner.
