### ISSUE TITLE
Filter list of battles by rating

### ISSUE THREAD

**Issue by Ketsuban** [Zarel/Pokemon-Showdown-Client#412]
I like watching other people battle on Showdown, but I tire of picking a battle at random from the hundred or more going on in OU at any given moment only to be greeted with noncompetitive players or people who still think Electivire is worth using. Would it be possible to provide a way to filter by rating so I can limit myself to watching players who actually want to be competent?

**Comment by Zarel** [comment]
Yes, this is planned.
