### ISSUE TITLE
[hidden for security reasons]

### ISSUE THREAD

**Issue by herpadurr** [Zarel/Pokemon-Showdown-Client#416]
[hidden for security reasons]

**Comment by Zarel** [comment]
Blah, you caught me. :|

This data is only used to detect ban evaders, nothing else. It was obfuscated and hidden very carefully in the hopes that ban evaders wouldn't find it.

Now that you've made it public knowledge, I guess I'll de-obfuscate it.

**Comment by Zarel** [comment]
Note that we already use Google Analytics, which records this data anyway and is mentioned in our privacy policy.

**Comment by herpadurr** [comment]
Actually I only found it because of the protocol changes that required an update of my own login server, because that part had to be stripped on the server side, before processing the data.

Google Analytics is fine for me, I can block that. But shady obfuscated code needs to be made public.

**Comment by Zarel** [comment]
Aww, you don't agree with doing it to catch spammers that evade our bans? :( I was hoping we could leave it in. I swear it's not used for anything else.

**Comment by monsanto** [comment]
> But shady obfuscated code needs to be made public.

This is easy to say when you don't run a server with 12k+ people on it at once

**Comment by Zarel** [comment]
So I should probably make some sort of statement about what went on here.

Basically, this guy uncovered a trick we use to detect spammers.

The trick we use does not involve any personal information, and is covered by our privacy policy.

http://pokemonshowdown.com/privacy
