### ISSUE TITLE
Some Mega icons only showing base mon

### ISSUE THREAD

**Issue by Layell** [Zarel/Pokemon-Showdown-Client#437]
Diancie
Audino
Lopuny
Gallade

From what I have known the mega icons are hard coded, but these for whatever reason do not change. See teambuilder for easy reference.

Yes they are there: http://play.pokemonshowdown.com/sprites/bwicons-sheet.png

**Comment by Zarel** [comment]
This should be fixed now. Please confirm.

**Comment by Ridaz** [comment]
Confirmed for fixed
(Only Hoopa-U left to be put on the sheet)

**Comment by Zarel** [comment]
Okay, let's leave this issue open for Hoopa-U.

**Comment by Layell** [comment]
You can close it now once you update that icon sheet I just sent you ; )
