### ISSUE TITLE
BW replays don't load BW animation sizes

### ISSUE THREAD

**Issue by Layell** [Zarel/Pokemon-Showdown-Client#450]
http://replay.pokemonshowdown.com/gen5ou-261435204

http://replay.pokemonshowdown.com/smogtours-gen5ou-62801

Most obvious with any flying mon.

I swore this was working fine before.

This is a replay only bug, works fine in battle.

**Comment by Slayer95** [comment]
Refs https://github.com/Zarel/Pokemon-Showdown/issues/1905

**Comment by Zarel** [comment]
iirc someone modified the loading code recently. I wonder what broke.

**Comment by Zarel** [comment]
I'm just going to add it to the replay page instead of messing with however the dynamic loader's implemented on the client.

**Comment by Zarel** [comment]
(Fixed)
