### ISSUE TITLE
Sprite positioning exception needed for gen 3-4 doubles

### ISSUE THREAD

**Issue by Layell** [Zarel/Pokemon-Showdown-Client#472]
http://i.imgur.com/cMg6vUn.png

just need an exception to get the bottom two on the same axis when using the past gen sprites. Having the opponents being more in center would be nice as well.

**Comment by Layell** [comment]
Sprite.prototype.animSummon = function (slot, instant) {
		this.x = slot * (this.isBackSprite ? -1 : 1) * -55;
		this.y = (this.isBackSprite ? -1 : 1) + 1;
		this.statbarOffset = 0;
		if (!this.isBackSprite) this.statbarOffset = 17 * slot;
		if (this.isBackSprite) this.statbarOffset = -28 * slot;

These dimensions produce: http://i.imgur.com/8EGPYlN.png which is a good offset for the backsprites, just needing a recenter and modifying the top statbars.

**Comment by Zarel** [comment]
Or we could possibly just position the bars as a separate element instead of part of the background.

**Comment by Layell** [comment]
While that could still be done if you would want to add the extra code to do so, we need them put on the same x axis regardless, which https://github.com/Zarel/Pokemon-Showdown-Client/pull/471 does.
