### ISSUE TITLE
Empty list element sticks to teamlist when dragging non-file entity

### ISSUE THREAD

**Issue by augmt** [Zarel/Pokemon-Showdown-Client#521]
[[image]](http://i.imgur.com/PPbuN86.png?1)

Dragging a non-file entity (like text or a hyperlink) while the Teambuilder is open will [stick `li.dragging` to the teamlist](https://github.com/Zarel/Pokemon-Showdown-Client/blob/ba636c8c59f1bffb1c9d79b6250fafc5c4158fcf/js/client-teambuilder.js#L423).

This happens because [the client assumes it's dragging a file](https://github.com/Zarel/Pokemon-Showdown-Client/blob/ba636c8c59f1bffb1c9d79b6250fafc5c4158fcf/js/client.js#L69-L73) and the entity's empty FileList bypasses [these conditions](https://github.com/Zarel/Pokemon-Showdown-Client/blob/ba636c8c59f1bffb1c9d79b6250fafc5c4158fcf/js/client-teambuilder.js#L419-L421).

`li.dragging` will remain on the teamlist until `updateTeamList()` is called.

**Comment by Zarel** [comment]
Why doesn't `updateTeamList` get called on dragend or whatever? Can you just make it do that?

**Comment by augmt** [comment]
[`updateTeamList` would get called on drop](https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/js/client-teambuilder.js#L436) but a non-file entity can't make it to that point.

Initially I wanted to know if you'd recommend amending [this condition](https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/js/client-teambuilder.js#L421), but how about if I add an else-if case to `defaultDropTeam` like the one below?

    else if (e.target.className !== 'team team-hover') {
        app.dragging = null;
        this.updateTeamList();
        return;
    }

**Comment by Zarel** [comment]
Yes, that works.

**Comment by Zarel** [comment]
Actually, wait, the condition you link to could be better if you have a way to detect whether or not the dragged thing is a non-file entity.

**Comment by augmt** [comment]
else if (e.originalEvent.dataTransfer.types.indexOf('text/html') >= 0) {
        // code
    }

**Comment by Zarel** [comment]
Wait, there's a `.types`? That changes everything...

**Comment by augmt** [comment]
How so?

**Comment by Zarel** [comment]
Well, it may or may not change everything... Mainly, security policy prevents me from figuring out the file extension of files dragged in, which is why we react roughly the same way for every file type. If I can still see the file type, we can still narrow it down a lot.
