### ISSUE TITLE
Chat timestamps don't activated in past

### ISSUE THREAD

**Issue by DaniellMesquita** [Zarel/Pokemon-Showdown-Client#557]
When user activates the timestamp in messages, this activated only in messages after the action, not in all messages.

**Comment by Zarel** [comment]
This is not a bug (many systems work this way), and it would be kind of prohibitive to fix.

**Comment by Zarel** [comment]
We would most likely accept a pull request that implements this, but since we do not consider this a bug and do not plan to improve this ourselves, I see no reason to keep an open issue on this.
