### ISSUE TITLE
Requesting missing files in order to get this client running

### ISSUE THREAD

**Issue by ThaHaxx** [Zarel/Pokemon-Showdown-Client#558]
The AGPL states:
> c) You must license **the entire work, as a whole, under this License to anyone who comes into possession of a copy**. This License will therefore apply, along with any applicable section 7 additional terms, to the whole of the work, and all its parts, regardless of how they are packaged. This License gives no permission to license the work in any other way, but it does not invalidate such permission if you have separately received it.

There are some files used in this project, but included in this repository, providing fundamental features of the client:
```
../pokemonshowdown.com/lib/ntbb-session.lib.php
../pokemonshowdown.com/config/servers.inc.php
../pokemonshowdown.com/news/include.php
../pokemonshowdown.com/news/embed.php
../replay.pokemonshowdown.com/replays.lib.php
../pokemonshowdown.com/lib/ntbb-database.lib.php
```

As these files are required to full run the client I request you to release these files in terms of the AGPL v3.

**Comment by Slayer95** [comment]
Those files are not part of the client...

**Comment by Zarel** [comment]
It's kind of ambiguous exactly how to interpret "entire work, as a whole". How annoying.

**Comment by Zarel** [comment]
Wait, it's not ambiguous at all.

Someone bound by the AGPL must _license_ the work to someone who comes into possession of a copy, but they're not under any obligation to help you come into possession of a copy.

So whether or not I'm bound by the AGPL, I'm not obligated to release these files,

**Comment by ThaHaxx** [comment]
Should turn on email notifications...

Preamble of the AGPL:

> When we speak of free software, we are referring to freedom, not price. Our General Public Licenses are designed **to make sure** that you have the freedom to distribute copies of free software (and charge for them if you wish), **that you receive source code or can get it if you want it**, that you can change the software or use pieces of it in new free programs, and that you know you can do these things.

So I ask again to release the source or examples of theses files!

**Comment by Zarel** [comment]
Well, I still don't know if I agree with that interpretation of the AGPL, but it's moot now because I'm consolidating those files in this repository, anyway:

82e7a917ab3d92d96
