### ISSUE TITLE
Timer in tournament challenge

### ISSUE THREAD

**Issue by DaniellMesquita** [Zarel/Pokemon-Showdown-Client#560]
Will be nice a timer in tour challenges that automatically disclassify inactive users.

**Comment by AustinXII** [comment]
that's already a thing.....

**Comment by AustinXII** [comment]
try ``/tour setautodq [time]``

**Comment by Zarel** [comment]
Maybe we should turn it on by default?

**Comment by Zarel** [comment]
@DaniellMesquita, you've opened incorrect issues several times now. In the future, could you ask one of our collaborators to make sure your issue isn't a mistake before posting it?

**Comment by DaniellMesquita** [comment]
@Zarel, Not turn it on by default, but give an button for user like happen on battles!

**Comment by DaniellMesquita** [comment]
In some tours that creator don't used /tour setautodq [time], users report that can't continue tour, depending of an dq of admin. I can't see reason to close this topic.

**Comment by AustinXII** [comment]
@DaniellMesquita if the tournament is being held up by someone then report it to a room mod/room owner, they can turn on the autodq. If none are available then a tournament shouldn't be running in the first place
