### ISSUE TITLE
Electro Ball ranges incorrect

### ISSUE THREAD

**Issue by hvk3** [Zarel/Pokemon-Showdown-Client#573]
This is because of the following code : 
var minRatio = (myPokemon.stats['spe'] / this.getTemplateMinSpeed(template, target.level));
var maxRatio = (myPokemon.stats['spe'] / this.getTemplateMaxSpeed(template, target.level));

It should be the other way around.

**Comment by Slayer95** [comment]
Could you send a pullreq?

**Comment by hvk3** [comment]
Corrected and sent in my last pull request.

**Comment by hvk3** [comment]
This issue has been resolved in my last pr. Should it be closed now?

**Comment by Slayer95** [comment]
Pass-by-fixed in https://github.com/hvk3/Pokemon-Showdown-Client/commit/df4cc30de474d41eac31f5194fb3e008fac6e57f
