### ISSUE TITLE
styling of download replay too different from upload & share replay button

### ISSUE THREAD

**Issue by EmmaRamirez** [Zarel/Pokemon-Showdown-Client#579]
This might be sort of opinionated, but it's really odd aesthetically that the download and upload buttons look so different on the site.

Unless there's a reason for it (I know one's an `<a>` tag and the other a `<button>`), then I think it'd make more sense from a UI standpoint to have them be similar.

**Comment by Zarel** [comment]
From a UI standpoint, the download button is new and is highlighted for that reason.

I also want to encourage people to download battles more.

**Comment by DanUgore** [comment]
Did the same thing for the downloadable client :|

**Comment by Zarel** [comment]
?
