### ISSUE TITLE
Popup issues on mobile when searching for a user

### ISSUE THREAD

**Issue by robot56** [Zarel/Pokemon-Showdown-Client#581]
Commit 42ddd81c680bc1b4d8bbf1d64d3cd1c057814016 seems to have broken the ''Find a user" option on the main menu on mobile devices. The window opens, but immediately closes afterwards. I've tested it on Android and iOS so it doesn't appear to be a browser-specific issue.

**Comment by robot56** [comment]
I've traced it down to this change in client.js:

```patch
@@ -2229,14 +2229,13 @@
  	});
  
  	var PromptPopup = this.PromptPopup = Popup.extend({
-		type: 'semimodal',
  		initialize: function (data) {
```

**Comment by Zarel** [comment]
Wow, good catch, and thanks for the detailed analysis of the reason.

**Comment by Zarel** [comment]
We no longer dismiss popups when resizing. Can you confirm that this issue is fixed?

**Comment by robot56** [comment]
Indeed, it seems to be working now :+1:
