### ISSUE TITLE
XY-style pokemon icons in battle screen

### ISSUE THREAD

**Issue by Zarel** [Zarel/Pokemon-Showdown-Client#590]
XY icons are now everywhere except in the battle screen, where they don't fit.

The battle screen will need to be severely redesigned if we want them to fit.

I reject any 2x3 arrangements as really ugly. On the other hand, 1x6 and 6x1 designs (suggested in the Dev room) are promising.

**Comment by Layell** [comment]
Here is a 1x6 design with the bonus of info we have to share at team preview, and info we ought to share.

https://i.imgur.com/RBbvYTN.png

**Comment by Zarel** [comment]
Really, that's all info that can be put in the mouseover. I'd rather have just the icons normally.

**Comment by ascriptmaster** [comment]
The problem with the Pokeball being there is that you don't know what Pokeball it is until the Pokemon is sent out. What would you put in the meantime?

**Comment by Layell** [comment]
4 variants then

1: It still might be nice to have the stuff shown on team preview
2: Just icons
3: Both columns aligned at top
4: You say you hate it, but I still think it's the best way. Plus it is consistent with how we already have the layout. The other just have too much vertical information.

**Comment by Marty-D** [comment]
Can we decide on this soon? I'm really not interested in supporting bwicons once Sun and Moon come out, and I'm sure Layell doesn't want to be doing [edits like this](http://i.imgur.com/AZNGRK3.png) again when he could be doing other things.

**Comment by Zarel** [comment]
I actually drew some actually good proposals, but honestly the squeeze trick we use for everything else works well enough here. Let's just do that for now.

**Comment by Layell** [comment]
This should be closed since this was changed now : )

http://i.imgur.com/1EJ1m0l.png
