### ISSUE TITLE
Redundant check in teambuilder

### ISSUE THREAD

**Issue by hvk3** [Zarel/Pokemon-Showdown-Client#599]
Lines 2587 and 2588 are doing the same checks.
if (stats.spa > stats.atk && moveCount['Special'] > 1) offenseBias = 'Special';
else if (stats.spa > stats.atk && moveCount['Special'] > 1) offenseBias = 'Special';

**Comment by Zarel** [comment]
Why not just pullreq the fix? o_O

**Comment by hvk3** [comment]
Done
