### ISSUE TITLE
Modernizing the client code

### ISSUE THREAD

**Issue by Slayer95** [Zarel/Pokemon-Showdown-Client#653]
(TBD)

---

Original OP:

Use `es5-shim` in the replay site.

Should allow us to drop Lodash, and keep (even gain!) all the compatibility we want to watch replays.

**Comment by Zarel** [comment]
lodash is a dependency for backbone. I don't think es5-shim gives us anything we use for the replay site at all, so I'm not sure why we're adding it.

**Comment by Slayer95** [comment]
Oh, I wasn't aware of that. It does give us some stuff we use though, such as ``Array#indexOf`` polyfill (``battledata.js``)

So if we didn't have it as a subdependency, ``es5-shim`` would allow us to start using ``Function#bind`` and ``Array#map`` instead of the Lodash function, as well as ``Array.isArray`` and ``String#trim`` instead of the jQuery functions.

Maybe we could still add ``es5-shim`` though... It feels very weird to call ``$.trim()``.

**Comment by Zarel** [comment]
`Array#indexOf` is ES5? Shit, I've been overusing it; we should possibly switch over to the lodash implementation.

**Comment by Zarel** [comment]
I also wasn't aware we used `Array#map` at all on client; I'd normally just use a for-loop.

**Comment by Slayer95** [comment]
Note that we already have a home-grown (actually from MDN iirc) polyfill for ``Array#indexOf``.

Anyway, when will we embrace ES5 in the client? To think that ES2016 (aka ES7) is already right here!

**Comment by Zarel** [comment]
We can unify it all to use lodash. I kind of prefer to know that I'm not using a native ES3 API instead of having all that hidden from me.

**Comment by Slayer95** [comment]
iirc, they tend to call the native methods if available, but I'd have to double check

**Comment by Zarel** [comment]
We can alternatively use Babel, I guess. We already have a compile step on the client. Or maybe TypeScript.

Generally, I'm a fan of having as few dependencies as possible.

**Comment by Zarel** [comment]
In unrelated news, we should get rid of our Sugar dependency on the server. It's unhealthy and also most of what we use have native methods anyway.

**Comment by Slayer95** [comment]
I am actually +1 on using Babel for the client now.
And RE: Sugar, yes we've already agreed on it. I wonder if Node v6 will get ``Object.values``...

**Comment by Zarel** [comment]
`for` and `Object.keys(...).map` does most of what we need from `Object.values`, I guess.

**Comment by Zarel** [comment]
Closing. Current state of client is fine to me. Maybe one day we'll port to TypeScript and then we can compile to ES3 and not worry about all that, but most likely we won't since who actually wants to do major refactors for free?
