### ISSUE TITLE
[Lint error] Duplicate identifier 'sandtomb' in data/graphics.js

### ISSUE THREAD

**Issue by mizdra** [Zarel/Pokemon-Showdown-Client#658]
In data/graphics.js, ``BattleMoveAnims.sandtomb`` properties are written at [line 7186](https://github.com/Zarel/Pokemon-Showdown-Client/blob/335794b8cd4c59089e0532e754222cb79578d4d2/data/graphics.js#L7186) and [line 10901](https://github.com/Zarel/Pokemon-Showdown-Client/blob/335794b8cd4c59089e0532e754222cb79578d4d2/data/graphics.js#L10901).

The former isn't used because the latter override the former in this case.
So I think one of those should be deleted.

An example is below:
```js
var obj = {
    a: 10,
    b: 20,
    a: 30
};
console.log(obj.a); // => 30
```

A replay is below:
- <http://replay.pokemonshowdown.com/1v1-337041825>

**Comment by Zarel** [comment]
@Ridaz, which one is the intended Sand Tomb animation? The other should be deleted.

**Comment by Zarel** [comment]
Also: Isn't this the sort of thing `eslint` is supposed to pick up? @Slayer95.

**Comment by ascriptmaster** [comment]
Ridaz wasn't involved in this one, the error apparently traces back over a year ago. `git blame` traces the duplication to #269, when I initially implemented the animation, meaning I accidentally duplicated it in the commit, and because the diff file was too big to show on the web client, nobody noticed the duplication.

Because they were implemented simultaneously on accident, the latter animation is the "intended" one.

**Comment by Zarel** [comment]
Fixed in 9cd878d5f, but I'm leaving this issue open for my question to @Slayer95.

**Comment by mizdra** [comment]
Thank you for fixing. :smiley:

> but I'm leaving this issue open for my question to @Slayer95.
I understand.

**Comment by Slayer95** [comment]
@Zarel, the ``data`` folder isn't covered yet.

Talking about which, we probably should add most of it to ``.gitignore``

**Comment by Zarel** [comment]
It's not added to `.gitignore` for the sole reason that that would make testing client changes a lot more annoying.

**Comment by Slayer95** [comment]
@Zarel, can't we just use the code from ``play.pokemonshowdown.com/data`` in ``testclient.html``?
It's not like those files are editted directly with any frequency, except for the few files remaining in source control after #660

**Comment by Zarel** [comment]
@Slayer95, I've had to develop PS offline a few times (seriously, nothing better to do when the US's third-world internet goes down), and for that I'm very thankful that the teambuilder fully works offline besides the images.

**Comment by Zarel** [comment]
Closing; move further discussion to #660.
