### ISSUE TITLE
Clicking buttons in battle using the keyboard

### ISSUE THREAD

**Issue by PatBouchard** [Zarel/Pokemon-Showdown-Client#696]
I've run into a problem where I can no longer press the buttons to attack or switch when using the latest version of IE. This used to work, I played for the first time in a couple of weeks today and this is the first time I've had the problem. It still works on Firefox and Chrome for Windows, but I have a totally different issue in those browsers, which I'll post separately if this one can't be resolved. I can't see my computer screen, so I use a screen reader program to use it. For this reason I can't use the mouse, so that's why I need to use the keyboard. Right now I have to type either /move or /switch, which is a bit unwieldy, or use a keystroke to simulate a mouse click, which is really unwieldy.
Have there been any changes to event handlers or something similar for buttons in combat? Or is this something weird on my end?

**Comment by Zarel** [comment]
Oh, we changed how tooltips work in mobile, that might have affected this. I'll look into it.

**Comment by Zarel** [comment]
Is `/move` a problem? It honestly seems like the best option for keyboard control.

**Comment by PatBouchard** [comment]
I could get used to it if it's not an easy thing to fix. Just have to
go down to look at the order if I've forgotten it, then have to come
back up to type. But it's doable.

**Comment by Zarel** [comment]
You can also use `/move [move name]` if you don't remember the order...?

**Comment by PatBouchard** [comment]
Aha, I didn't know that, didn't even know about /move at all until I
brought this up in the help chatroom. Sorry for taking your time,
then, I probably could've researched a little more before coming here.

**Comment by Zarel** [comment]
Well, this _is_ still a bug; let's leave this open until we fix it

**Comment by Zarel** [comment]
With no leads, my best suspicion is just a temporary bug in IE, so closing.

PS doesn't do anything weird with our move buttons; just a `click` handler on a regular button.
