### ISSUE TITLE
Pokémon shown stuck in air when hitting itself

### ISSUE THREAD

**Issue by Nixola** [Zarel/Pokemon-Showdown-Client#717]
When a pokémon uses Fly (I guess it applies to other moves as well, didn't test it though) and, in the second turn, hits itself in confusion, it will still appear to be flying even though it's actually on ground. It's just a visual bug, so I guess it's not really high priority, but it can be misleading. It's visible on the replay as well: http://replay.pokemonshowdown.com/hackmonscup-377495505

**Comment by Slayer95** [comment]
This happens in Turn 32
