### ISSUE TITLE
Mega Evolution not Working on Website

### ISSUE THREAD

**Issue by magibolt** [Zarel/Pokemon-Showdown-Client#718]
I'm not sure if it's just a problem with the online version, or if it's something wrong with how I make my Pokemon, but whenever I put in a Pokemon as (Pokemon Name)-Mega, or (Pokemon Name) With its Mega Stone as an item, it doesn't allow me to mega during the battle.
![mega evolution not working](https://cloud.githubusercontent.com/assets/19575436/15548244/25713f12-226d-11e6-9880-1178dc015d47.jpg)

**Comment by Zarel** [comment]
It looks like this is a problem with a browser extension you've installed, not with PS itself.
