### ISSUE TITLE
Teambuilder: Only show Spiky-eared Pichu for [Gen 4] formats

### ISSUE THREAD

**Issue by TheImmortal** [Zarel/Pokemon-Showdown-Client#719]
Can Spiky-eared Pichu not show up in the teambuilder unless the format is prefixed with [Gen 4]? There's absolutely no reason it should be always shown because it's a Pokemon exclusive to HGSS. People actually try to use it in current gen, and even in gen 5.

I have no clue where to do this. You can direct me where it should go or do it yourself.

**Comment by Marty-D** [comment]
Cosplay Pikachu and its costumed alter egos will be needing similar treatment soon, considering it can't be placed in Bank or traded to XY, and is thus locked in ORAS forever.

**Comment by Zarel** [comment]
Shouldn't it show up as Illegal?

**Comment by Zarel** [comment]
Apparently it doesn't. We need to fix this...

**Comment by HoeenCoder** [comment]
Pretty sure if this is fixed since Spiky-Eared Pichu and the Cosplay Pikachu's are showing up as `Illegal` in teambuilder for all gens except 4 and 6 respectivly.

**Comment by Zarel** [comment]
That's very weird since I've done nothing to change this afaik.

Like, I'm pretty sure I implemented teambuilder tier lists before September 2016...

Oh well, if it's fixed as a side effect of a different fix, that's less work for us.
