### ISSUE TITLE
Autojoin fails depending on window width...?

### ISSUE THREAD

**Issue by Morfent** [Zarel/Pokemon-Showdown-Client#742]
I find autojoin works fine when the window's wide enough to display the button list (Battle!, Teambuilder, etc.) at the far left of the page while focused on a room, but if the window is narrow enough to prevent it from displaying, autojoin fails for whatever reason. This has been happening for several months now, but I haven't been able to find any other explanation as to why this happens.

Tested on Firefox 47.0 (x64) and Chromium 51.0.2704.103 (x64).

**Comment by Zarel** [comment]
This is intentional, and dates from before autojoin existed, even before rooms other than Lobby existed.

Back then, it didn't really make sense to join a room if you couldn't even see it.

I guess autojoin changes things, though. The question is, how? Discuss.

**Comment by Morfent** [comment]
Two ways:
- it's inconsistent with joining rooms on connect depending on the route, like [https://psim.us/lobby](url), which will attempt to join lobby regardless of the width of the window
- the point of autojoin was to allow users to be able to join the rooms they were in last time they were on PS. I don't think this should be dependent on something as obtuse as window width when either having to remember to resize the window before refreshing or going to the site or forgetting and being forced to join each room manually somewhat defeats the purpose of the feature in the first place. 
It may have been helpful when lobby was the only room, but I think over the years it has become a bad design choice to continue with.

**Comment by Morfent** [comment]
Does anyone else have any comments?

bump
