### ISSUE TITLE
Joining a room via the "Join other room" button, using room abbreviations/initials causes the tab to close after opening

### ISSUE THREAD

**Issue by Meeplee** [Zarel/Pokemon-Showdown-Client#755]
As the title describes, if you join a room, throught the "Join Other Room" button, on the chatrooms list, if you use the shortname for a room, it will close the tab opened suddenly.

For an example, using "overused" to join works properly, but "ou" doesn't.

https://streamable.com/ynmx (Example Video)

I've tested this to happen under Firefox (Windows & OSX) and Safari (OSX), a friend confirms it to happen on Chrome (Windows) aswell.

**Comment by panpawn** [comment]
I believe this issue has been patched.

**Comment by Zarel** [comment]
You're right, it has.
