### ISSUE TITLE
Delay from clicking "Battle!" button

### ISSUE THREAD

**Issue by panpawn** [Zarel/Pokemon-Showdown-Client#767]
I think that often times, when a user accidentally clicks the "Battle!" button on Main, there is nearly always an instantaneous battle that they get.  I think there should be a **three second delay** from clicking the Battle button until it actually starts searching - this would give users a fair amount of time to click "cancel" if they didn't intend on clicking the Battle button.

**Comment by CrestfallPS** [comment]
+1 to this. Has happened more than I like to admit.

**Comment by Zarel** [comment]
I'm fine with this.

**Comment by QuiteQuiet** [comment]
Is this better done on the client or server?

**Comment by panpawn** [comment]
I made a PR for this server-side: https://github.com/Zarel/Pokemon-Showdown/pull/2811

**Comment by acz13** [comment]
#775

**Comment by acz13** [comment]
Just kidding it's #776

**Comment by panpawn** [comment]
good job @acz13 !

**Comment by acz13** [comment]
Haha good thing javascript doesn't throw an error when you clear something that doesn't exist

lol js is so messed up
