### ISSUE TITLE
Animation Capability 

### ISSUE THREAD

**Issue by Lord-Haji** [Zarel/Pokemon-Showdown-Client#817]
PS doesn't support animation capabilities for its background with its custom.css

**Comment by Zarel** [comment]
Duplicate of #248

**Comment by Zarel** [comment]
I believe the last five things you've submitted to PS's issue tracker do nothing but waste time. I would suggest talking about things in the Dev chatroom first, because this is untenable and I really don't want the issue tracker to be full of this sort of thing.
