### ISSUE TITLE
Move in battle chat button on mobile to left hand side. 

### ISSUE THREAD

**Issue by atn2001** [Zarel/Pokemon-Showdown-Client#820]
![screenshot_2016-11-25-21-34-57](https://cloud.githubusercontent.com/assets/15368682/20637509/43297192-b358-11e6-9da5-b5f4836874fe.png)
On mobile the chat button likes to cover your opponents username. As a possible fix I suggest moving it to the left hand side

**Comment by Zarel** [comment]
This isn't really a suggestions tracker... Anyway I think I'd rather move the Chat button up and the username down.

**Comment by atn2001** [comment]
I couldnt really find where to put the suggestions. However moving the username down could work.
