### ISSUE TITLE
Autojoin support for sideservers

### ISSUE THREAD

**Issue by panpawn** [Zarel/Pokemon-Showdown-Client#848]
When autojoin was introduced, I remember it saying that support for sideservers would become a thing, and it since has not.

I think supporting this for sideservers would be a nice feature.

**Comment by HoeenCoder** [comment]
This would be a great addition, one thing to handle is how do you keep autojoin separate for different servers & main? Obviously different servers have different rooms and I don't think having your autojoin selection change everytime you switch to a different server will help, in fact it would hurt more than it would help.

**Comment by panpawn** [comment]
> one thing to handle is how do you keep autojoin separate for different servers & main?

Easy, one way of doing that is just having a sub-object held with the serverid if it's not main that contains the room ids.

**Comment by HoeenCoder** [comment]
Since the format of `Tools.prefs('autojoin')` (contains autojoin info) is a string with rooms seperated by commas, what about seperating servers with ``]`` and have the server id listed before the rooms?

Example:
```javascript
var autojoin = "smogonuniversity,lobby,development]spacialgaze,lobby,development]gold,lobby,development";
// each server
let servers = autojoin.split(']');
for (let i = 0; i < servers.length; i++) {
  let data = servers[i].split(',');
  // Server ID
  let server = servers.shift();
  // Rooms === servers[i]
}

```

**Comment by HoeenCoder** [comment]
For a working copy, id probably loop till i found the right server, (default to `''` for no autojoin), then `break;` that loop and run the normal autojoin setup with the roomlist from the server

**Comment by panpawn** [comment]
Why not just literally use objects based on serverids if the severid isn't ``showdown``?

**Comment by HoeenCoder** [comment]
I could do that, maybe it would be best to use a format such as

```javascript
var autojoin = {
  showdown: "lobby,tournaments,development",
  spacialgaze: "lobby,development",
  gold: "lobby,development",
};
```
over the current string setup, as its getting a bit messy with having to parse it twice (once to get the server, then the rooms)

**Comment by panpawn** [comment]
sure, something to that effect is what I meant

**Comment by HoeenCoder** [comment]
Ok, that also allows for
```javascript
if (typeof autjoin === 'String') {
	autojoin = {showdown: autjoin};
}
```
which will come in handy transfering over to the new object setup

**Comment by HoeenCoder** [comment]
@panpawn this can be closed now.
