### ISSUE TITLE
Desync on servers which don't autojoin the lobby

### ISSUE THREAD

**Issue by AndrioCelos** [Zarel/Pokemon-Showdown-Client#884]
When joining an unofficial server (via `psim.us`) which doesn't autojoin clients to the `lobby` chat room, the client doesn't seem to realise it never actually joined the lobby. The lobby chat tab opens with an empty user list and no messages, and entering `/join lobby` in the box does nothing until the tab is closed.

**Comment by Zarel** [comment]
This is a server issue. Fixed here:

https://github.com/Zarel/Pokemon-Showdown/commit/a24fdf8a5185fd65bdac0ae367f13efac1229665
