### ISSUE TITLE
Package name should be lowercase

### ISSUE THREAD

**Issue by FelixRilling** [Zarel/Pokemon-Showdown-Client#904]
Currently the name in the package.json is `Pokemon-Showdown-Client` 
https://github.com/Zarel/Pokemon-Showdown-Client/blob/master/package.json#L2

It is considered best practice to have the [name be lowercase only](https://docs.npmjs.com/files/package.json).

The Pokemon Showdown server has a lowercase-name already
https://github.com/Zarel/Pokemon-Showdown/blob/master/package.json#L2

**Comment by Zarel** [comment]
You really don't need a separate issue if you're going to make a pullreq for them...
