### ISSUE TITLE
Opera crashes in teambuilder

### ISSUE THREAD

**Issue by asgdf** [Zarel/Pokemon-Showdown-Client#911]
There have been multiple reports of Opera crashing when opening/using the teambuilder. I am able to reproduce this using Opera's newest version. The issue seems to be calling ``navigator.storage.persist()`` (as introduced by https://github.com/Zarel/Pokemon-Showdown-Client/commit/b3b2eea2f218745b20f56dc135b2445e0c0c9af2), which immediately crashes the browser for me (this happens regardless of how or where it's called, even in the browser console of a blank tab).
I've submitted a bug report for Opera, until that gets fixed I suppose we might want to prevent Opera users from executing that part of the code? I'd do it, but I don't know the extent of the issue, maybe it's just the windows version or the 32 bit version or something.

**Comment by FelixRilling** [comment]
I tested and reproduced this issue on Windows10/Opera 44(x64)

**Comment by FelixRilling** [comment]
After more research I isolated the problem in the following code:
```js
navigator.storage.persisted().then(function (state) {
 	console.log(state)
});
```
This crashes Opera but works in all other browsers

**Comment by AustinXII** [comment]
@FelixRilling asgdf already stated that in the issue

**Comment by FelixRilling** [comment]
Yes, I just wanted to confirm the stated problem.

**Comment by AustinXII** [comment]
@FelixRilling ah makes sense although it seems kinda redundant to just reiterate what was already said.

**Comment by Zarel** [comment]
If someone wants to rig up an Opera detector?

**Comment by asgdf** [comment]
Would checking the user agent for "OPR" or "opera" be enough?

**Comment by Zarel** [comment]
I'd actually only detect a specific version of Opera, the version that crashes.

**Comment by xfix** [comment]
![zrzut ekranu z 2017-06-28 18-52-19](https://user-images.githubusercontent.com/1297598/27649830-3bf70d7e-5c33-11e7-869a-25dc8a285128.png)

Seems to have been fixed in Opera 46? I cannot get Opera to crash even when changing user agent, when I was able to do this before with changed user agent.

**Comment by Zarel** [comment]
@xfix feel free to update the test in #912
