### ISSUE TITLE
PM Refactor

### ISSUE THREAD

**Issue by panpawn** [Zarel/Pokemon-Showdown-Client#961]
PMs could be much improved; they haven't changed much since added to PS.

Some of the bigger issues with PMs are log-tracking, report-ability, and not taking up much space.

For starters, if I close PS, my PMs with everyone I was PMing will be gone.  If I reported someone, I could easily fake a screen cap to get someone else in trouble.  If I am having a long conversation with someone, it can be tedious to do so on such a small window.

One of the things that would change this is if PMs were re-worked into room-like tabs, and maybe even actual rooms like groupchats.

If you made PMs groupchat-type rooms, where they were limited to those two people, the server would keep the conversation up even if a user closed PS.  The report feature would be relatively easily done server-side as well.  

If a "room" is a PM, then we could create a PM-tabs bar under the room-tabs bar.  This would organize PMs, while also keeping them separate from actual rooms.

This is just one idea; there's lots of other ways that PMs can be improved.

**Comment by Zarel** [comment]
We don't already have an issue for this? I already have a detailed plan for this sketched out somewhere.

**Comment by panpawn** [comment]
I didn't see an issue for this, unless I missed it?

**Comment by Zarel** [comment]
https://github.com/Zarel/Pokemon-Showdown/issues/2151

This one.

**Comment by panpawn** [comment]
Oh, my bad...
