### ISSUE TITLE
Illusion

### ISSUE THREAD

**Issue by Zarel** [Zarel/Pokemon-Showdown-Client#987]
Illusion screws with the client two ways:

Say you have a Zoroark, Illusioned as a Venusaur.

- If Zoroark faints from move damage, both Zoroark and Venusaur will be treated by the client as fainted.
- If Zoroark faints from residual damage, Venusaur will be treated by the client as fainted.

General plan to deal with this:

- Venusaur should be brought back to life (full HP, no status) if it's revealed to be Zoroark during the faint process (move damage case)
- Zoroark should be marked as fainted if Venusaur is switched in after it faints (residual damage case)

This can't cover Hackmons. I'm thinking of a `|legality|` message to cover things like Species Clause and whether or not hacked mons are allowed, which will give the client more information to work with in terms of what it can assume does and doesn't have Illusion.

**Comment by QuiteQuiet** [comment]
Did you want to resolve the direct damage purely client side or not? Since it seems that the problem is the server sending somewhat confusing messages when the Illusion ends.

    |-damage|p2a: Slowbro|0 fnt      <- this bit seems to be what confuses the client for direct damage?
    |replace|p2a: Zoroark|Zoroark, M
    |-end|p2a: Zoroark|Illusion
    |faint|p2a: Zoroark

**Comment by Zarel** [comment]
This is resolvable with "Venusaur should be brought back to life (full HP, no status) if it's revealed to be Zoroark during the faint process (move damage case)" during the `|replace|` step.

**Comment by QuiteQuiet** [comment]
Doesn't that add more complications if whatever the Illusion was has previously been in. Showing a full HP, no status Pokemon if the reality is a 45% hp, burned Pokemon doesn't seem to be a lot better?

**Comment by Zarel** [comment]
It's a lot better than showing a fainted pokemon if the reality is a 45% HP burned Pokémon.

And remember, the actual reality is sometimes impossible for the player to know (beyond "statused/unstatused") because they don't know which of the previous switch-ins was or wasn't Zoroark.

It _is_ possible, in most cases, to figure it out, but requires a significant amount of client code.

**Comment by Zarel** [comment]
- Venusaur should be brought back to life (full HP, no status) if it's revealed to be Zoroark during the faint process (move damage case)

Implemented in 5cd7e0040c225455f7a4feb1a9ee1d769e3b5f5a

- Zoroark should be marked as fainted if Venusaur is switched in after it faints (residual damage case)

Implemented in 289aa0cdb1eb0b17e9e5329199c585f032a04e32

**Comment by urkerab** [comment]
> `|-damage|p2a: Slowbro|0 fnt`

On ROM I changed this to `|-damage|p2a: Slowbro|0` and it seemed to help, but unfortunately I never got around to PRing it.

**Comment by Zarel** [comment]
It shouldn't make a difference. Either way, the commits mentioned above should fully fix the issue.
