### ISSUE TITLE
Sort battles by "rated" field

### ISSUE THREAD

**Issue by Tegawende** [Zarel/Pokemon-Showdown-Client#990]
Hello, Is it possible to sort the list of battles before displaying it to the user who want to watch them ?

**Comment by Zarel** [comment]
No, but it's not what you want anyway. If you want to watch a battle in-process, the "Watch" screen should show newest battles first. If you want to watch a battle that's already over, you should be using the replay database.

So what really needs to happen is to support sorting by rating in the replay database. Which... I guess I'll get to one day...
